# Generated by Django 3.2.3 on 2021-06-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='height_field',
            field=models.PositiveIntegerField(default=60, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='width_field',
            field=models.PositiveIntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='height_field',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='specialty',
            name='width_field',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(
                blank=True,
                default='100x60.gif',
                height_field='height_field',
                upload_to='MEDIA_COMPANY_IMAGE_DIR',
                width_field='width_field',
            ),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(
                default='100x60.gif',
                height_field='height_field',
                upload_to='MEDIA_SPECIALITY_IMAGE_DIR',
                width_field='width_field',
            ),
        ),
    ]
