# Generated by Django 3.2.3 on 2021-06-05 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0002_auto_20210605_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='height_field',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(
                default='100x60.gif',
                height_field='height_field',
                upload_to='MEDIA_COMPANY_IMAGE_DIR',
                width_field='width_field',
            ),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(
                default='Нет пользователя',
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='user',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='company',
            name='width_field',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
