# Generated by Django 3.2.3 on 2021-06-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20210605_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
