# Generated by Django 3.2.3 on 2021-06-12 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0005_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applications',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(max_length=30)),
                ('specialty', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=400)),
                ('experience', models.CharField(max_length=400)),
                ('portfolio', models.CharField(max_length=200)),
                ('owner', models.OneToOneField(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='resume_owner',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
    ]
