# Generated by Django 3.2.3 on 2021-06-13 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0006_auto_20210612_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[('INT', 'Intern'), ('JR', 'Junior'), ('MID', 'Middle'), ('SNR', 'Senior'), ('LD', 'Lead')], max_length=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_spec', to='vacancies.specialty'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='surname',
            field=models.CharField(choices=[('NIS', 'Не ищу работу'), ('CON', 'Рассматриваю предложения'), ('INS', 'Ищу работу')], max_length=3),
        ),
    ]
