# Generated by Django 3.2.3 on 2021-06-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_auto_20210614_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('NIS', 'Не ищу работу'), ('CON', 'Рассматриваю предложения'), ('INS', 'Ищу работу')], max_length=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
